main: water.of.cup.cameras.Camera
name: Cameras
version: @project.version@
description: Take Pictures.
author: Nicholas Kopiwoda
api-version: 1.17
commands:
  takepicture:
    description: take a picture